/* Creación vistas para facilitar carga de datos */

CREATE VIEW catalogo_medicamentos AS SELECT * FROM MEDICAMENTO@qro UNION SELECT * FROM MEDICAMENTO@qropv2;
CREATE VIEW catalogo_ventas AS SELECT * FROM venta@qro UNION SELECT * FROM venta@qropv2;
CREATE VIEW catalogo_ventas_partidas AS SELECT * FROM venta_partida@qro UNION SELECT * FROM venta_partida@qropv2;
CREATE VIEW catalogo_empleados AS SELECT * FROM empleado@qro UNION SELECT * FROM empleado@qropv2;
CREATE VIEW catalogo_clientes AS SELECT * FROM cliente@qro UNION SELECT * FROM cliente@qropv2;
CREATE VIEW catalogo_inventario AS SELECT * FROM inventario@qro UNION SELECT * FROM inventario@qropv2;
CREATE VIEW catalogo_proveedores AS SELECT * FROM proveedor@qro UNION SELECT * FROM proveedor@qropv2;
CREATE VIEW catalogo_punto_de_venta AS SELECT * FROM punto_de_venta@qro UNION SELECT * FROM punto_de_venta@qropv2;
CREATE VIEW catalogo_compras AS SELECT * FROM compra@qro UNION SELECT * FROM compra@qropv2;

/* SEQ */

CREATE SEQUENCE  SEQ_D_CLIENTE_VENTAS_CLIENTE  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  SEQ_D_EMPLEADO_VENTAS_EMPLEADO  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 401 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  SEQ_D_MEDICAMENTO_COMPRAS_PROV  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  SEQ_D_MEDICAMENTO_INVENTARIO  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  SEQ_D_MEDICAMENTO_VENTAS  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 801 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  SEQ_D_PROVEEDOR_COMPRAS_PROV  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  SEQ_D_TIEMPO  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 741 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  SEQ_H_COMPRAS_PROVEEDOR  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  SEQ_H_INVENTARIO  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  SEQ_H_VENTAS_CLIENTE  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  SEQ_H_VENTAS_EMPLEADO  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

/* DIMENSION TIEMPO */

CREATE TABLE D_TIEMPO(
    ID NUMBER PRIMARY KEY, 
    FECHA DATE, 
    ANIO VARCHAR2(4), 
    MES VARCHAR2(30), 
    DIA NUMBER(10), 
    NOMBRE_DIA VARCHAR2(20)
);


/* HECHOS VENTAS EMPLEADO */

CREATE TABLE D_MEDICAMENTO_VENTAS(
    ID NUMBER PRIMARY KEY, 
    VENTA_PARTIDA_ID NUMBER, 
    VENTA_ID NUMBER,
    MEDICAMENTO_ID NUMBER,
    NOMBRE VARCHAR2(50),
    INGREDIENTE_ACTIVO VARCHAR2(50),
	PUNTO_DE_VENTA_ID NUMBER,
	NOMBRE_PUNTO_DE_VENTA VARCHAR2(50)
);

CREATE TABLE D_EMPLEADO_VENTAS_EMPLEADO(
    ID NUMBER PRIMARY KEY, 
    EMPLEADO_ID NUMBER, 
	NOMBRE VARCHAR2(50),
	APELLIDOS VARCHAR2(50)
);

CREATE TABLE H_VENTAS_EMPLEADO(
    ID NUMBER PRIMARY KEY,
    D_TIEMPO_ID NUMBER,
    D_MEDICAMENTO_ID NUMBER, 
    D_EMPLEADO_ID NUMBER,
    CANTIDAD NUMBER,
	COSTO NUMBER,
    CONSTRAINT D_TIEMPO_EMPLEADO_FK FOREIGN KEY(D_TIEMPO_ID) REFERENCES D_TIEMPO(ID),
    CONSTRAINT D_MEDICAMENTO_EMPLEADO_FK FOREIGN KEY(D_MEDICAMENTO_ID) REFERENCES D_MEDICAMENTO_VENTAS(ID),
    CONSTRAINT D_EMPLEADO_EMPLEADO_FK FOREIGN KEY(D_EMPLEADO_ID) REFERENCES D_EMPLEADO_VENTAS_EMPLEADO(ID)
);

/* HECHOS VENTAS CLIENTE */

CREATE TABLE D_CLIENTE_VENTAS_CLIENTE(
    ID NUMBER PRIMARY KEY, 
    CLIENTE_ID NUMBER, 
    NOMBRE VARCHAR2(50),
	APELLIDOS VARCHAR2(50),
    COLONIA VARCHAR2(50),
    FECHA_ALTA DATE
);

CREATE TABLE H_VENTAS_CLIENTE(
    ID NUMBER PRIMARY KEY,
    D_TIEMPO_ID NUMBER,
    D_MEDICAMENTO_ID NUMBER, 
    D_CLIENTE_ID NUMBER,
    CANTIDAD NUMBER,
	COSTO NUMBER,
    CONSTRAINT D_TIEMPO_CLIENTE_FK FOREIGN KEY(D_TIEMPO_ID) REFERENCES D_TIEMPO(ID),
    CONSTRAINT D_MEDICAMENTO_CLIENTE_FK FOREIGN KEY(D_MEDICAMENTO_ID) REFERENCES D_MEDICAMENTO_VENTAS(ID),
    CONSTRAINT D_CLIENTE_CLIENTE_FK FOREIGN KEY(D_CLIENTE_ID) REFERENCES D_CLIENTE_VENTAS_CLIENTE(ID)
);

/* HECHOS INVENTARIO */

CREATE TABLE D_MEDICAMENTO_INVENTARIO(
    ID NUMBER PRIMARY KEY,
    MEDICAMENTO_ID NUMBER,
	NOMBRE_MEDICAMENTO VARCHAR2(50),
    PUNTO_DE_VENTA_ID NUMBER,
    NOMBRE_PUNTO_DE_VENTA VARCHAR2(100)
);

CREATE TABLE H_INVENTARIO(
    ID NUMBER PRIMARY KEY,
    D_MEDICAMENTO_ID NUMBER,
    D_TIEMPO_ID NUMBER, 
    CADUCIDAD DATE,
    CONSTRAINT D_MEDICAMENTO_INVENTARIO_FK FOREIGN KEY(D_MEDICAMENTO_ID) REFERENCES D_MEDICAMENTO_INVENTARIO(ID),
    CONSTRAINT D_TIEMPO_INVENTARIO_FK FOREIGN KEY(D_TIEMPO_ID) REFERENCES D_TIEMPO(ID)
);


/* COMPRAS PROVEEDOR */

CREATE TABLE D_PROVEEDOR_COMPRAS_PROV (
  ID number primary key,
  PROVEEDOR_ID number,
  NOMBRE varchar2(50)
);

CREATE TABLE D_MEDICAMENTO_COMPRAS_PROV (
  ID number primary key,
  COMPRA_ID number,
  MEDICAMENTO_ID number,
  NOMBRE_MEDICAMENTO varchar2(50),
  PUNTO_DE_VENTA_ID number,
  NOMBRE_PUNTO_DE_VENTA varchar2 (100)
);


CREATE TABLE H_COMPRAS_PROVEEDOR (
  ID number primary key,
  D_MEDICAMENTO_ID number,
  D_TIEMPO_ID number,
  D_PROVEEDOR_ID number,
  CANTIDAD NUMBER,
  COSTO NUMBER,
  CONSTRAINT D_MEDICAMENTO_COMPRAS_PROV_FK FOREIGN KEY(D_MEDICAMENTO_ID) REFERENCES D_MEDICAMENTO_COMPRAS_PROV(ID),
  CONSTRAINT D_TIEMPO_FK FOREIGN KEY(D_TIEMPO_ID) REFERENCES D_TIEMPO(ID),
  CONSTRAINT D_PROVEEDOR_FK FOREIGN KEY(D_PROVEEDOR_ID) REFERENCES D_PROVEEDOR_COMPRAS_PROV(ID)
);
