/* DROP VISTAS */
DROP VIEW catalogo_medicamentos;
DROP VIEW catalogo_ventas;
DROP VIEW catalogo_ventas_partidas;
DROP VIEW catalogo_empleados;
DROP VIEW catalogo_clientes;
DROP VIEW catalogo_inventario;
DROP VIEW catalogo_proveedores;
DROP VIEW catalogo_punto_de_venta;
DROP VIEW catalogo_compras;

/* DROP PREGUNTAS*/

DROP VIEW compras_proveedor_mes;
DROP VIEW medicamentos_mas_vendidos_mes;
DROP VIEW no_ventas_clientes_año;
DROP VIEW ventas_clientes_mes;
DROP VIEW ventas_empleado_mes;
DROP VIEW ventas_medicamento_año;
DROP VIEW ventas_sucursal1_mes;
DROP VIEW ventas_sucursal2_mes;

/* DROP SECUENCIAS */

DROP SEQUENCE SEQ_D_CLIENTE_VENTAS_CLIENTE;
DROP SEQUENCE SEQ_D_EMPLEADO_VENTAS_EMPLEADO;
DROP SEQUENCE SEQ_D_MEDICAMENTO_COMPRAS_PROV;
DROP SEQUENCE SEQ_D_MEDICAMENTO_INVENTARIO;
DROP SEQUENCE SEQ_D_MEDICAMENTO_VENTAS;
DROP SEQUENCE SEQ_D_PROVEEDOR_COMPRAS_PROV;
DROP SEQUENCE SEQ_D_TIEMPO;
DROP SEQUENCE SEQ_H_COMPRAS_PROVEEDOR;
DROP SEQUENCE SEQ_H_INVENTARIO;
DROP SEQUENCE SEQ_H_VENTAS_CLIENTE;
DROP SEQUENCE SEQ_H_VENTAS_EMPLEADO;

/* DROP DIMENSIONES */

DROP TABLE D_TIEMPO CASCADE CONSTRAINTS;
DROP TABLE D_MEDICAMENTO_VENTAS CASCADE CONSTRAINTS;
DROP TABLE D_EMPLEADO_VENTAS_EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE H_VENTAS_EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE D_CLIENTE_VENTAS_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE H_VENTAS_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE D_MEDICAMENTO_INVENTARIO CASCADE CONSTRAINTS;
DROP TABLE H_INVENTARIO CASCADE CONSTRAINTS;
DROP TABLE D_PROVEEDOR_COMPRAS_PROV CASCADE CONSTRAINTS;
DROP TABLE D_MEDICAMENTO_COMPRAS_PROV CASCADE CONSTRAINTS;
DROP TABLE H_COMPRAS_PROVEEDOR CASCADE CONSTRAINTS;



