
/* HECHOS VENTAS EMPLEADO */

DROP TABLE D_TIEMPO_VENTAS_EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE D_MEDICAMENTO_VENTAS_EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE D_EMPLEADO_VENTAS_EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE H_VENTAS_EMPLEADO CASCADE CONSTRAINTS;

CREATE TABLE D_TIEMPO_VENTAS_EMPLEADO(
    ID NUMBER PRIMARY KEY, 
    FECHA DATE, 
    ANIO VARCHAR2(4), 
    MES VARCHAR2(30), 
    DIA NUMBER(10), 
    NOMBRE_DIA VARCHAR2(20)
);

CREATE TABLE D_MEDICAMENTO_VENTAS_EMPLEADO(
    ID NUMBER PRIMARY KEY, 
    VENTA_PARTIDA_ID NUMBER, 
    VENTA_ID NUMBER,
    MEDICAMENTO_ID NUMBER,
    NOMBRE VARCHAR2(255),
    INGREDIENTE_ACTIVO VARCHAR2(255)
);

CREATE TABLE D_EMPLEADO_VENTAS_EMPLEADO(
    ID NUMBER PRIMARY KEY, 
    EMPLEADO_ID NUMBER, 
    PUNTO_DE_VENTA_ID NUMBER,
    NOMBRE VARCHAR2(255),
    NOMBRE_PUNTO_DE_VENTA VARCHAR2(255)
);

CREATE TABLE H_VENTAS_EMPLEADO(
    ID NUMBER PRIMARY KEY,
    D_TIEMPO_ID NUMBER,
    D_MEDICAMENTO_ID NUMBER, 
    D_EMPLEADO_ID NUMBER,
    CANTIDAD NUMBER,
    CONSTRAINT D_TIEMPO_EMPLEADO_FK FOREIGN KEY(D_TIEMPO_ID) REFERENCES D_TIEMPO_VENTAS_EMPLEADO(ID),
    CONSTRAINT D_MEDICAMENTO_EMPLEADO_FK FOREIGN KEY(D_MEDICAMENTO_ID) REFERENCES D_MEDICAMENTO_VENTAS_EMPLEADO(ID),
    CONSTRAINT D_EMPLEADO_EMPLEADO_FK FOREIGN KEY(D_EMPLEADO_ID) REFERENCES D_EMPLEADO_VENTAS_EMPLEADO(ID)
);

/* HECHOS VENTAS CLIENTE */

DROP TABLE D_TIEMPO_VENTAS_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE D_MEDICAMENTO_VENTAS_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE D_CLIENTE_VENTAS_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE H_VENTAS_CLIENTE CASCADE CONSTRAINTS;

CREATE TABLE D_TIEMPO_VENTAS_CLIENTE(
    ID NUMBER PRIMARY KEY, 
    FECHA DATE, 
    ANIO VARCHAR2(4), 
    MES VARCHAR2(30), 
    DIA NUMBER(10), 
    NOMBRE_DIA VARCHAR2(20)
);

CREATE TABLE D_MEDICAMENTO_VENTAS_CLIENTE(
    ID NUMBER PRIMARY KEY, 
    VENTA_PARTIDA_ID NUMBER, 
    VENTA_ID NUMBER,
    MEDICAMENTO_ID NUMBER,
    NOMBRE VARCHAR2(255),
    INGREDIENTE_ACTIVO VARCHAR2(255)
);

CREATE TABLE D_CLIENTE_VENTAS_CLIENTE(
    ID NUMBER PRIMARY KEY, 
    CLIENTE_ID NUMBER, 
    NOMBRE VARCHAR2(255),
    COLONIA VARCHAR2(255),
    FECHA_ALTA DATE
);

CREATE TABLE H_VENTAS_CLIENTE(
    ID NUMBER PRIMARY KEY,
    D_TIEMPO_ID NUMBER,
    D_MEDICAMENTO_ID NUMBER, 
    D_CLIENTE_ID NUMBER,
    CANTIDAD NUMBER,
    CONSTRAINT D_TIEMPO_CLIENTE_FK FOREIGN KEY(D_TIEMPO_ID) REFERENCES D_TIEMPO_VENTAS_CLIENTE(ID),
    CONSTRAINT D_MEDICAMENTO_CLIENTE_FK FOREIGN KEY(D_MEDICAMENTO_ID) REFERENCES D_MEDICAMENTO_VENTAS_CLIENTE(ID),
    CONSTRAINT D_CLIENTE_CLIENTE_FK FOREIGN KEY(D_CLIENTE_ID) REFERENCES D_CLIENTE_VENTAS_CLIENTE(ID)
);

/* HECHOS INVENTARIO */

DROP TABLE D_TIEMPO_INVENTARIO;
DROP TABLE D_MEDICAMENTO_INVENTARIO;
DROP TABLE H_INVENTARIO;

CREATE TABLE D_TIEMPO_INVENTARIO(
    ID NUMBER PRIMARY KEY, 
    FECHA DATE, 
    ANIO VARCHAR2(4), 
    MES VARCHAR2(30), 
    DIA NUMBER(10), 
    NOMBRE_DIA VARCHAR2(20)
);

CREATE TABLE D_MEDICAMENTO_INVENTARIO(
    ID NUMBER PRIMARY KEY,
    MEDICAMENTO_ID NUMBER,
    PUNTO_DE_VENTA_ID NUMBER,
    NOMBRE_MEDICAMENTO VARCHAR2(255),
    NOMBRE_PUNTO_DE_VENTA VARCHAR2(255)
);

CREATE TABLE H_INVENTARIO(
    ID NUMBER PRIMARY KEY,
    D_MEDICAMENTO_ID NUMBER,
    D_TIEMPO_ID NUMBER, 
    CADUCIDAD DATE,
    CONSTRAINT D_MEDICAMENTO_INVENTARIO_FK FOREIGN KEY(D_MEDICAMENTO_ID) REFERENCES D_MEDICAMENTO_INVENTARIO(ID),
    CONSTRAINT D_TIEMPO_INVENTARIO_FK FOREIGN KEY(D_TIEMPO_ID) REFERENCES D_TIEMPO_INVENTARIO(ID)
);
