/* VENTASGRAL */

CREATE OR REPLACE VIEW VENTASGRAL AS	
SELECT "ID","EMPLEADO_ID","CLIENTE_ID","PUNTO_DE_VENTA_ID","FECHA","SUBTOTAL","IVA","TOTAL"
FROM VENTA
UNION
SELECT "ID","EMPLEADO_ID","CLIENTE_ID","PUNTO_DE_VENTA_ID","FECHA","SUBTOTAL","IVA","TOTAL"
FROM VENTA@pv2;

/* INVENTARIOGRAL */
CREATE OR REPLACE VIEW INVENTARIOGRAL AS
SELECT "ID","MEDICAMENTO_ID","PUNTO_DE_VENTA_ID","FECHA_ADQUISICION","FECHA_CADUCIDAD"
FROM INVENTARIO
UNION
SELECT "ID","MEDICAMENTO_ID","PUNTO_DE_VENTA_ID","FECHA_ADQUISICION","FECHA_CADUCIDAD"
FROM INVENTARIO@pv2;

/* COMPRASGRAL */
CREATE OR REPLACE VIEW COMPRASGRAL AS
SELECT "ID","PROVEEDOR_ID","MEDICAMENTO_ID","PUNTO_DE_VENTA_ID","FECHA","CANTIDAD"
FROM COMPRA
UNION
SELECT "ID","PROVEEDOR_ID","MEDICAMENTO_ID","PUNTO_DE_VENTA_ID","FECHA","CANTIDAD" 
FROM COMPRA@pv2;