/* SECUENCIAS PARA LOS ÍNDICES DE LAS TABLAS */

DROP SEQUENCE SEQ_CLIENTE;
DROP SEQUENCE SEQ_MEDICAMENTO;
DROP SEQUENCE SEQ_PROVEEDOR;
DROP SEQUENCE SEQ_COMPRA;
DROP SEQUENCE SEQ_VENTA_PARTIDA;
DROP SEQUENCE SEQ_INVENTARIO;
DROP SEQUENCE SEQ_VENTA;
DROP SEQUENCE SEQ_EMPLEADO;
DROP SEQUENCE SEQ_PUNTO_DE_VENTA;
DROP SEQUENCE SEQ_TRANSFERENCIA;

CREATE SEQUENCE SEQ_CLIENTE  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE SEQ_MEDICAMENTO  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE SEQ_PROVEEDOR  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE SEQ_COMPRA  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE SEQ_VENTA_PARTIDA  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE SEQ_INVENTARIO  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE SEQ_VENTA  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE SEQ_EMPLEADO  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE SEQ_PUNTO_DE_VENTA  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE SEQ_TRANSFERENCIA  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

/* CREACIÓN DE LAS TABLAS */

DROP TABLE PROVEEDOR CASCADE CONSTRAINTS;
DROP TABLE MEDICAMENTO CASCADE CONSTRAINTS;
DROP TABLE PUNTO_DE_VENTA CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE COMPRA CASCADE CONSTRAINTS;
DROP TABLE COMPRA CASCADE CONSTRAINTS;
DROP TABLE INVENTARIO CASCADE CONSTRAINTS;
DROP TABLE EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE VENTA CASCADE CONSTRAINTS;
DROP TABLE VENTA_PARTIDA CASCADE CONSTRAINTS;
DROP TABLE TRANSFERENCIA CASCADE CONSTRAINTS;

CREATE TABLE PROVEEDOR (
  ID number primary key,
  NOMBRE varchar2(50),
  DIRECCION varchar2(100) default NULL,
  TELEFONO varchar2(20) default NULL
);

CREATE TABLE MEDICAMENTO (
  ID number primary key,
  NOMBRE varchar2(50),
  INGREDIENTE_ACTIVO varchar2(50) default NULL,
  CONTENIDO varchar2(50),
  PRESENTACION varchar2(50) default NULL
);

CREATE TABLE PUNTO_DE_VENTA (
  ID number primary key,
  NOMBRE varchar2(50),
  DIRECCION varchar2(100) default NULL,
  TELEFONO varchar2(20) default NULL
);

CREATE TABLE CLIENTE (
  id number primary key,
  NOMBRE varchar2(50) default NULL,
  APELLIDOS varchar2(500) default NULL,
  RFC varchar2(100),
  CALLE varchar2(50),
  COLONIA varchar2(50),
  TELEFONO varchar2(20) default NULL,
  FECHA_ALTA date
);

CREATE TABLE COMPRA (
  ID number primary key,
  PROVEEDOR_ID number default NULL,
  MEDICAMENTO_ID number default NULL,
  PUNTO_DE_VENTA_ID number default NULL,
  FECHA date,
  CANTIDAD number default NULL,
  PRECIO number(10,2) default NULL,
  CONSTRAINT COMPRA_PROVEEDOR_FK FOREIGN KEY(PROVEEDOR_ID) REFERENCES PROVEEDOR(id),
  CONSTRAINT COMPRA_MEDICAMENTO_FK FOREIGN KEY(MEDICAMENTO_ID) REFERENCES MEDICAMENTO(id),  
  CONSTRAINT COMPRA_PUNTO_DE_VENTA_FK FOREIGN KEY(PUNTO_DE_VENTA_ID) REFERENCES PUNTO_DE_VENTA(id)
);

CREATE TABLE INVENTARIO (
  ID number primary key,
  MEDICAMENTO_ID number default NULL,
  PUNTO_DE_VENTA_ID number default NULL,
  FECHA_ADQUISICION date,
  FECHA_CADUCIDAD date,
  CANTIDAD number default NULL,
  PRECIO number(10,2) default NULL,
  CONSTRAINT INVENTARIO_PUNTO_DE_VENTA_FK FOREIGN KEY(PUNTO_DE_VENTA_ID) REFERENCES PUNTO_DE_VENTA(id),
  CONSTRAINT INVENTARIO_MEDICAMENTO_FK FOREIGN KEY(MEDICAMENTO_ID) REFERENCES MEDICAMENTO(id) 
);

CREATE TABLE EMPLEADO (
  ID number primary key,
  NOMBRE varchar2(50) default NULL,
  APELLIDOS varchar2(50) default NULL,
  FECHA_NACIMIENTO date,
  TELEFONO varchar2(20) default NULL,
  PUNTO_DE_VENTA_ID number default NULL,
  CONSTRAINT EMPLEADO_PUNTO_DE_VENTA_FK FOREIGN KEY(PUNTO_DE_VENTA_ID) REFERENCES PUNTO_DE_VENTA(id)
);

CREATE TABLE VENTA (
  ID number primary key,
  EMPLEADO_ID number default NULL,
  CLIENTE_ID number default NULL,
  PUNTO_DE_VENTA_ID number default NULL,
  FECHA date,
  SUBTOTAL number(10,2) default NULL,
  IVA number(10,2) default NULL,
  TOTAL number(10,2) default NULL,
  CONSTRAINT VENTA_EMPLEADO_FK FOREIGN KEY(EMPLEADO_ID) REFERENCES EMPLEADO(id),
  CONSTRAINT VENTA_CLIENTE_FK FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTE(id),
  CONSTRAINT VENTA_PUNTO_DE_VENTA FOREIGN KEY(PUNTO_DE_VENTA_ID) REFERENCES PUNTO_DE_VENTA(id)
);

CREATE TABLE VENTA_PARTIDA (
  ID number primary key,
  VENTA_ID number default NULL,
  INVENTARIO_ID number default NULL,
  PRECIO number(10,2) default NULL,
  CANTIDAD number default NULL,
  MONTO number(10,2) default NULL,
  CONSTRAINT VENTA_PARTIDA_VENTA_FK FOREIGN KEY(VENTA_ID) REFERENCES VENTA(id),
  CONSTRAINT VENTA_PARTIDA_INVENTARIO_FK FOREIGN KEY(INVENTARIO_ID) REFERENCES INVENTARIO(id)
);

CREATE TABLE TRANSFERENCIA (
  ID number primary key,
  PUNTO_DE_VENTA_ID_DEST Number,
  PUNTO_DE_VENTA_ID_ORIG Number default NULL,
  INVENTARIO_ID_ORIG NUMBER default NULL,
  CONSTRAINT PUNTO_DE_VENTA_ID_ORIG_FK FOREIGN KEY(PUNTO_DE_VENTA_ID_ORIG) REFERENCES PUNTO_DE_VENTA(id),
  CONSTRAINT INVENTARIO_ID_ORIG_FK FOREIGN KEY(INVENTARIO_ID_ORIG) REFERENCES INVENTARIO(id)
);
