/* CREAVENTA */
CREATE OR REPLACE PROCEDURE CREAVENTA 
(
  EMPLEADO_ID IN NUMBER 
, CLIENTE_ID IN NUMBER 
, PUNTO_DE_VENTA_ID IN NUMBER 
) AS 
BEGIN
  INSERT INTO VENTA VALUES (seq_venta.nextval, EMPLEADO_ID, CLIENTE_ID, PUNTO_DE_VENTA_ID, TO_DATE(sysdate, 'DD/MM/YYYY HH:MI:SS'), 0, 0, 0);
  COMMIT;
  NULL;
END CREAVENTA;

/* AGREGAPARTIDA */
CREATE OR REPLACE PROCEDURE AGREGAPARTIDA 
(
  VENTA_ID IN NUMBER 
, INVENTARIO_ID IN NUMBER 
, CANTIDAD IN NUMBER 
) AS 

  cant NUMBER;
  pre NUMBER;
BEGIN
    SELECT cantidad INTO cant FROM INVENTARIO WHERE ID = INVENTARIO_ID;
    IF cant < CANTIDAD THEN
      RAISE_APPLICATION_ERROR(-20101, 'No hay suficientes productos en el almacén');
    ELSE
      SELECT precio INTO pre FROM INVENTARIO WHERE ID = INVENTARIO_ID;
      INSERT INTO VENTA_PARTIDA VALUES (SEQ_VENTA_PARTIDA.NEXTVAL, VENTA_ID, INVENTARIO_ID, pre, CANTIDAD, CANTIDAD * pre); 
      UPDATE VENTA SET SUBTOTAL = SUBTOTAL + (pre * CANTIDAD) WHERE ID = VENTA_ID;
      SELECT SUBTOTAL INTO cant FROM VENTA WHERE ID = VENTA_ID;
      UPDATE VENTA SET IVA = cant * 0.16 WHERE ID = VENTA_ID;
      SELECT IVA INTO pre FROM VENTA WHERE ID = VENTA_ID;
      UPDATE VENTA SET TOTAL = cant + pre WHERE ID = VENTA_ID;
    END IF;
  COMMIT;
  NULL;
END AGREGAPARTIDA;