INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
ZIAGEN','Ergotamina','17 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'ORENCIA','Esencia de clavo','24 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'REOPRO','Ceftriaxona','07 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'PRECOSE','Estavudina','76 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
SECTRAL','Olmesartán medoxomilo','12 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
DIAMOX','Ondansetrón','31 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
MEPRON','Oxerutinas','18 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
AZELEX','Estreptodornasa','13 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
ZITHROMAX','Auranofina','38 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
LIORESAL','Bacitracina','97 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'SIMULECT','Benzatina penicilina G','92 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
ZUPRAX','Subsalicilato de bismuto','43 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
ZEBETA','Bisoprolol','22 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'PEPTO-BISMOL','Subsalicilato de bismuto','68 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
URECHOLINE','Betaxolol','19 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'TESSALON','Bimatoprost','26 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'COGENTIN','Bepridilo','49 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'DULCOLAX','Bisacodilo','55 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
MYLERAN','Buspirona','71 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
STADOL','Butoconazol','01 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'ZOSTRIX','Capsaicina','40 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
CAPSIN','Capsaicina','81 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CAPZASIN','Capsaicina','18 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
CALTRATE','Carbonato de calcio','50 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'OS-CAL','Carbonato de calcio','50 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'TUMS','Carbonato de calcio','35 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
ANCEF','Cefazolina','50 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'KEFZOL','Cefazolina','67 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'OMNICEF','Cefdinir','15 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'SPECTRACEF','Cefditoren','79 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'MAXIPIME','Cefepima','82 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
CLAFORAN','Cefotaxima','18 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
MEFOXIN','Cefoxitina','02 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'VANTIN','Cefpodoxima','40 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CEFZIL','Cefprozilo','20 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'FORTAZ','Ceftazidima','22 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'TAZICEF','Ceftazidima','65 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CEDAX','Ergotamina','46 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CEFIZOX','Esencia de clavo','78 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'ZEFTERA','Ceftriaxona','54 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'ROCEPHIN','Estavudina','30 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CEFTIN','Olmesartán medoxomilo','94 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'ZINACEF','Ondansetrón','56 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CELEBREX','Oxerutinas','87 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CELECTOL','Estreptodornasa','79 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'KEFLEX','Auranofina','03 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'ZYRTEC','Bacitracina','90 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'EVOXAC','Benzatina penicilina G','24 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'LEUKERAN','Subsalicilato de bismuto','95 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CLORANFENICOL','Bisoprolol','71 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'LIBRIUM','Subsalicilato de bismuto','20 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'HIBICLENS','Betaxolol','66 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'LEUSTATIN','Bimatoprost','21 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'ARALEN','Bepridilo','52 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'DIURIL','Bisacodilo','81 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CHLOR-TRIMETON','Buspirona','65 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
DIABINESE','Butoconazol','45 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'THALITONE','Carbonato de calcio','37 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'PARAFON FORTE','Cefdinir','10 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'QUESTRAN','Cefditoren','75 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'LOPROX','Cefepima','50 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'VISTIDE','Cefdinir','22 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
PLETAL','Cefpodoxima','69 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'TAGAMET','Cefprozilo','21 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'MODALIM','Ergotamina','68 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CILOXAN','Esencia de clavo','84 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CIPRO','Ceftriaxona','77 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'PLATINOL','Ceftriaxona','84 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CELEXA','Cefditoren','42 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CLEOCIN','Cefditoren','17 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CLOBEX','Bimatoprost','11 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'TEMOVATE','Olmesartán medoxomilo','29 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CLODERM','Olmesartán medoxomilo','97 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CLODERM','Estavudina','83 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'LAMPRENE','Estavudina','06 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CLOMID','Olmesartán medoxomilo','31 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'SEROPHENE','Benzatina penicilina G','98 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'ANAFRANIL','Benzatina penicilina G','01 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
KLONOPIN','Daptomicina','60 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
CATAPRES','Dalfopristina','03 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'PLAVIX','Dalfopristina','46 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'TRANXENE','Daptomicina','73 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'LOTRIMIN AF','Fenofibrato','59 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'MYCELEX','Fexofenadina','08 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CLOXAPEN','Fexofenadina','51 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CLORAZIL','Haloperidol','54 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
DENOREX','Haloperidol','41 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'NEUTROGENA T/GEL','Hexaclorofeno','68 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'WELCHOL','Ifosfamida','38 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'COLESTID','Ifosfamida','46 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'COLY-MYCIN M','Imatinib','16 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CORTEF','Imatinib','67 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CROLOM','Irinotecán','72 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'	
MAREZINE','766973-5651','11 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CYCLOGYL','Lorazepam','31 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CYTOXAN LIOFILIZADO','Mafenida','95 g.','Jarabe');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'NEORAL','Memantina','88 g.','Inyectable');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'SANDIMMUNE','Metilprednisolona','74 g.','Pastilla');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'ANDROCUR','Nitrazepam','90 g.','Capsula');
INSERT INTO MEDICAMENTO (ID,NOMBRE,INGREDIENTE_ACTIVO,CONTENIDO,PRESENTACION) VALUES (SEQ_MEDICAMENTO.NEXTVAL,'CYTOSAR-U','Olsalazina','21 g.','Jarabe');

